### ISSUE TITLE
Make social auth integration optional and include settings

### ISSUE THREAD

**Issue by jacelo** [mugna-tech/django-template#176]
Acceptance Criteria:
- [x] Social auth should be optional in cooker cutter template
- [x] Add options to setup pre-setup config for common social auth
  - [x] Google
  - [x] Facebook
  - [x] Apple
  - [x] GitHub
  - [x] X(Twitter)
  - [x] LinkedIn

**Comment by Whitneypi3** [comment]
@rzykie kindly assign effort estimate for this tix please. Thanks!

**Comment by rzykie** [comment]
done

**Comment by rzykie** [comment]
October 10, 2024:

Research: 3 hours
Implementation: 2 hours
